#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
xrandr -s 1920x1080 &

bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		 31

bspc config normal_border_color 	"#111212"
bspc config active_border_color 	"#006796"
bspc config focused_border_color 	"#FF000000"

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^8' follow=on layer=above border=off
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Google-chrome desktop='^2' follow=on border=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Automatically start up programs
picom &
feh --bg-fill ~/wallpapers/default-wallpaper.jpg &
nitrogen --restore &
pulseaudio --kill &
sleep 2
pulseaudio --start &
xscreensaver -nosplash &
$HOME/.config/polybar/run-polybar.sh &
